name: build

on:
  push:
    branches:
    - main
    - master
    - '*deploy*'
    tags:
    - v*
  pull_request:


jobs:
  tests:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest] #, osx-latest]
        python: ["3.8","3.10","3.11", "pypy-3.8"]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Install hatch
      run: pip install hatch
    - id: pyname_fix
      run: python -c "import sys;print('pyversion=' + sys.argv[1].replace('pypy-', 'pypy'))" ${{ matrix.python }} >> $GITHUB_OUTPUT
    - name: Test
      run: hatch run +py=${{ steps.pyname_fix.outputs.pyversion }} test:test --color=yes

  deploy:

    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')

    runs-on: ubuntu-latest

    needs: tests

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.7"
    - name: Install hatch
      run: pip install hatch
    - name: Build package
      run: hatch build
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.pypi_token }}
