name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        name: [
            "windows-py27",
            "windows-py35",
            "windows-py36",
            "windows-py37",
            "windows-py38",
            "windows-py39",

            "linux-py27",
            "linux-py35",
            "linux-py36",
            "linux-py37",
            "linux-py38",
            "linux-py39",

            "linux-pypy2",
            "linux-pypy3",
        ]
        include:
          - name: "windows-py27"
            python: "2.7"
            tox_env: "py27"
            os: "windows-latest"
          - name: "windows-py35"
            python: "3.5"
            tox_env: "py35"
            os: "windows-latest"
          - name: "windows-py36"
            python: "3.6"
            tox_env: "py36"
            os: "windows-latest"
          - name: "windows-py37"
            python: "3.7"
            tox_env: "py37"
            os: "windows-latest"
          - name: "windows-py38"
            python: "3.8"
            tox_env: "py38"
            os: "windows-latest"
          - name: "windows-py39"
            python: "3.9"
            tox_env: "py39"
            os: "windows-latest"

          - name: "linux-py27"
            python: "2.7"
            tox_env: "py27"
            os: "ubuntu-latest"
          - name: "linux-py35"
            python: "3.5"
            tox_env: "py35"
            os: "ubuntu-latest"
          - name: "linux-py36"
            python: "3.6"
            tox_env: "py36"
            os: "ubuntu-latest"
          - name: "linux-py37"
            python: "3.7"
            tox_env: "py37"
            os: "ubuntu-latest"
          - name: "linux-py38"
            python: "3.8"
            tox_env: "py38"
            os: "ubuntu-latest"
          - name: "linux-py39"
            python: "3.9"
            tox_env: "py39"
            os: "ubuntu-latest"

          - name: "linux-pypy2"
            python: "pypy-2.7"
            tox_env: "pypy2"
            os: "ubuntu-latest"
          - name: "linux-pypy3"
            python: "pypy-3.7"
            tox_env: "pypy3"
            os: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install tox setuptools_scm
      run: |
        python -m pip install --upgrade pip
        pip install tox setuptools_scm
    - name: Test
      run: |
        tox -e ${{ matrix.tox_env }}

  deploy:

    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')

    runs-on: ubuntu-latest

    needs: build

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.7"
    - name: Install wheel
      run: |
        python -m pip install --upgrade pip
        pip install wheel
    - name: Build package
      run: |
        python setup.py sdist bdist_wheel
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.pypi_token }}
